from django.urls import path
from . import views

urlpatterns = [
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout_repay/<int:order_id>/', views.checkout_repay, name='checkout_repay'),
    path('checkout/addingaddress/',views.checkoutaddress,name='checkoutaddress'),
    path('checkout/edit_address/<int:pk>/', views.editing_address, name='editing_address'),
    path('addressess/delete/<int:pk>/', views.deleting_address, name='deleting_address'),
    path('place_order/', views.place_order, name='place_order'),
    path('order_placed/<int:order_id>/', views.order_placed, name='order_placed'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order_history/', views.order_history, name='order_history'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('invoice/view/<int:order_id>/', views.view_invoice, name='view_invoice'),
    path('invoice/<int:order_id>/', views.invoice, name='invoice'),
    path('payments/', views.payments, name='payments'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove_coupon/', views.remove_coupon, name='remove_coupon'),
    path('manage_coupons/', views.manage_coupons, name='manage_coupons'),
    path('wallet/', views.wallet, name='wallet'),
    path('fetch_coupons/', views.fetch_coupons, name='fetch_coupons'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('checkout_repay/<int:order_id>/', views.checkout_repay, name='checkout_repay'),
]
