# Generated by Django 5.0.6 on 2024-06-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
