# Generated by Django 5.0.6 on 2024-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
