# Generated by Django 5.0.6 on 2024-07-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
