# Generated by Django 5.0.6 on 2024-07-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
