# Generated by Django 5.0.6 on 2024-07-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_remove_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
