# Generated by Django 5.0.6 on 2024-07-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
