# Generated by Django 5.0.6 on 2024-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_cart_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
