# Generated by Django 5.0.6 on 2024-08-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0031_cartitem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discounted_price',
        ),
    ]
