# Generated by Django 5.0.6 on 2024-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewratingz'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
