# Generated by Django 5.0.6 on 2024-07-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
