# Generated by Django 5.0.6 on 2024-07-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
