# Generated by Django 5.0.6 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
