# Generated by Django 5.0.6 on 2024-07-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_additional_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
    ]
