# Generated by Django 5.0.6 on 2024-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product_gallery'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
