# Generated by Django 5.0.6 on 2024-08-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productgallery_options_remove_product_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralOffer',
        ),
    ]
