# Generated by Django 5.0.6 on 2024-08-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_brand_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_deleted',
        ),
    ]
