# Generated by Django 5.0.6 on 2024-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, unique=True,null=True),
        ),
    ]
