# Generated by Django 5.0.6 on 2024-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
