# Generated by Django 5.0.6 on 2024-08-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_wow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wow',
        ),
    ]
