# Generated by Django 5.0.6 on 2024-08-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userprofile_wow'),
    ]

    operations = [
    ]
