# Generated by Django 5.0.6 on 2024-08-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_resolve_duplicate_referral_codes'),
    ]

    operations = [
    ]
